### ISSUE TITLE
Roadmap for Grav 1.5

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav#1977]
This issue is a shortcut to Grav 1.5 features and progress.

Following features and changes have currently been planned for Grav 1.5.0. The list is not definitive and may change based on changing priorities and ongoing progress:

* [x] Raise minimum requirement to [PHP 5.6.4](https://getgrav.org/blog/raising-php-requirements-2018)
* [x] Update Doctrine Collections to 1.4
* [x] Update Symfony Components to 3.4
* [x] Fix YAML issues as YAML 3.4 has more strict parsing rules
* [x] Improved session handling (#1933)
* [x] Fix multisite and multilanguage routing issues (#1511)

NOTE: Requires `rockettheme/toolbox` release!

**Comment by rhukster** [comment]
Added the process handling improvements we've discussed.  Might be just added to Admin plugin.

**Comment by mahagr** [comment]
Roadmap items postponed to Grav 1.6 has been moved into #2054
