### ISSUE TITLE
Roadmap for Grav 1.6

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav#2054]
This issue is a shortcut to Grav 1.6 features and progress.

Following features and changes have currently been planned for Grav 1.6.0. The list is not definitive and may change based on changing priorities and ongoing progress:

* [x] Requirements updated to [PHP 7.1.3](https://getgrav.org/blog/raising-php-requirements-2018)
* [x] Symfony 4.1 components
* [x] Doctrine Collections 1.5
* [x] Doctrine Cache 1.8
* [x] Task scheduler / CRON like functionality
* [x] Improved Backup functionality - more control/options
* [x] Namespace doctrine Cache and add prune old cache feature
* [x] New Flex Object classes
* [x] Asset manager rewrite too improve reliability and features set
* [ ] Parsedown 1.8 compatibility (#1972)
* [ ] Investigate better process handling (replace `onShutdown` which is not reliable on some setups)

**Comment by urc** [comment]
It's worth noting that PHP 7.1 hasn't really landed in any of the Linux LTS distributions aside from Ubuntu Bionic, which is still fairly new. Both Debian Stretch and Ubuntu Xenial ship with PHP 7.0, and don't yet have PHP 7.1 available as an option, either as separate packages or via backports. This might change before December, but they might also elect to backport security fixes instead.

Dotdeb also seems to cap out at 7.0, at the moment.

RHEL/CentOS has support for newer PHP versions via SCL, but that too depends on your hosting provider actually supporting it, instead of simply depending on the distribution packages.

**Comment by rhukster** [comment]
Add "Improve Backup functionality" .... Along with "Scheduler" integration, I would like to have some config options to provide more control.

**Comment by mahagr** [comment]
FYI:  There is a progress update in my first comment.

**Comment by OleVik** [comment]
@rhukster From a clean installation of 1.6-branch from Git, as well as Admin v1.8.9, here are a few notes from testing on Windows in /admin/config:

- Backups:
  - Admin:
    - Needs translations for BACKUPS_HISTORY, BACKUPS_PURGE_CONFIG, BACKUPS_PROFILES
    - The first field has no use? (image 1)
    - Backup-button on Dashboards yells "Class 'Grav\Common\Backup\ZipBackup' not found"
- Scheduler:
  - Admin:
    - Needs translations for SCHEDULER_SETUP, SCHEDULER_STATUS, SCHEDULER_JOBS
    - First and second fields are empty (image 2)
    - "Run Scheduled Job": Needs a description, linking to https://en.wikipedia.org/wiki/Cron
  - CLI:
    - `bin/grav scheduler --install` yields `(crontab -l; echo "* * * * * cd C:/Caddy/Grav;C:\Caddy\php\php.exe bin/grav scheduler 1>> /dev/null 2>&1") | crontab -` on Windows, it should just return "Create a scheduled task, see learn.getgrav.org/advanced/scheduler" or something to that effect
    - `bin/grav scheduler -d`, with no actually run jobs, defaults to 0 - yielding "1970-01-01 01:00" for "Last Run"

**Image 1:**
![image](https://user-images.githubusercontent.com/974717/46248593-93585180-c41b-11e8-9f2d-455db9a44eb8.png)

**Image 2:**
![image](https://user-images.githubusercontent.com/974717/46248595-9a7f5f80-c41b-11e8-97bd-5c521535a998.png)

**Comment by rhukster** [comment]
@OleVik You need the 1.9 branch of Admin to go with 1.6 of Grav, the updates are in there.

**Comment by pquerner** [comment]
Is 1.6 compatible with plugins/themes created on 1.5 (or earlier) ?

**Comment by rhukster** [comment]
Yes, everything should be compatible.

**Comment by mahagr** [comment]
Yes, Grav 1.6 should be mostly compatible with Grav 1.5. There are some edge cases, though, which will not work in the new version because of some architectural changes or fixes that have been made, but those should be rare and it was worth of risk to improve the code.

Of course, there may also be bugs, so please test the RC release(s) with your site and report of any problems. :)
